version: '3'
services:
  soa-mongo:
    container_name: soa-mongo
    image: mongo:latest
    ports:
    - "0.0.0.0:27017:27017"

  soa-broker:
    container_name: soa-broker
    image: rabbitmq:3.8-rc-management
    ports: 
    - "0.0.0.0:5672:5672"
    - "0.0.0.0:15672:15672"

  soa-sensor:
    build:
      context: ./
      dockerfile: ./dockerfiles/Dockerfile.SensorService
    image: soa/sensor-service
    volumes: 
      - /home/nemanja/soa_data:/data
    depends_on:
      - soa-registry
      - soa-broker
    ports:
    - "5001:5000"

  soa-registry:
    container_name: soa-registry
    build:
      context: ./
      dockerfile: ./dockerfiles/Dockerfile.SensorRegistry
    image: soa/sensor-registry
    depends_on:
      - soa-broker
    ports:
    - "5002:5000"

  soa-collector:
    build:
      context: ./
      dockerfile: ./dockerfiles/Dockerfile.CollectorService
    image: soa/collector-service
    depends_on:
      - soa-broker
      - soa-mongo
      - soa-registry
    ports:
    - "5003:5000"

