version: '3'
services:
  soa-mongo-db:
    container_name: soa-mongo-db
    image: mongo:latest
    ports:
    - "0.0.0.0:27017:27017"

  soa-broker:
    container_name: soa-broker
    image: rabbitmq:3.8-management
    ports: 
    - "0.0.0.0:5672:5672"
    - "0.0.0.0:15672:15672"

  soa-sensor:
    build:
      context: ./
      dockerfile: ./dockerfiles/Dockerfile.SensorService
    image: soa/sensor-service
    volumes: 
      - /home/nemanja/soa_data:/data
    # depends_on:
    #   - soa-registry
    #   - soa-broker
    ports:
    - "5001:5000"

  soa-registry:
    container_name: soa-registry
    build:
      context: ./
      dockerfile: ./dockerfiles/Dockerfile.SensorRegistry
    image: soa/sensor-registry
    # depends_on:
    #   - soa-broker
    ports:
    - "5002:5000"

  soa-collector:
    container_name: soa-collector
    build:
      context: ./
      dockerfile: ./dockerfiles/Dockerfile.CollectorService
    image: soa/collector-service
    # depends_on:
    #   - soa-broker
    #   - soa-registry
    #   - soa-mongo-db
    ports:
    - "5003:5000"

  soa-service-observer:
    container_name: soa-service-observer
    build:
      context: ./
      dockerfile: ./dockerfiles/Dockerfile.ServiceObserver
    image: soa/service-observer
    # depends_on:
    #   - soa-broker 
    #   - soa-mongo-db      
    ports:
    - "5004:5000"
  
  soa-data-observer:
    container_name: soa-data-observer
    build:
      context: ./
      dockerfile: ./dockerfiles/Dockerfile.ServiceObserver
    image: soa/data-observer
    ports:
      - "5005:5000"