public class SensorValues {
public string timestamp { get; set; }
public string raw_acc-magnitude_stats-mean { get; set; }
public string raw_acc-magnitude_stats-std { get; set; }
public string raw_acc-magnitude_stats-moment3 { get; set; }
public string raw_acc-magnitude_stats-moment4 { get; set; }
public string raw_acc-magnitude_stats-percentile25 { get; set; }
public string raw_acc-magnitude_stats-percentile50 { get; set; }
public string raw_acc-magnitude_stats-percentile75 { get; set; }
public string raw_acc-magnitude_stats-value_entropy { get; set; }
public string raw_acc-magnitude_stats-time_entropy { get; set; }
public string raw_acc-magnitude_spectrum-log_energy_band0 { get; set; }
public string raw_acc-magnitude_spectrum-log_energy_band1 { get; set; }
public string raw_acc-magnitude_spectrum-log_energy_band2 { get; set; }
public string raw_acc-magnitude_spectrum-log_energy_band3 { get; set; }
public string raw_acc-magnitude_spectrum-log_energy_band4 { get; set; }
public string raw_acc-magnitude_spectrum-spectral_entropy { get; set; }
public string raw_acc-magnitude_autocorrelation-period { get; set; }
public string raw_acc-magnitude_autocorrelation-normalized_ac { get; set; }
public string raw_acc-3d-mean_x { get; set; }
public string raw_acc-3d-mean_y { get; set; }
public string raw_acc-3d-mean_z { get; set; }
public string raw_acc-3d-std_x { get; set; }
public string raw_acc-3d-std_y { get; set; }
public string raw_acc-3d-std_z { get; set; }
public string raw_acc-3d-ro_xy { get; set; }
public string raw_acc-3d-ro_xz { get; set; }
public string raw_acc-3d-ro_yz { get; set; }
public string proc_gyro-magnitude_stats-mean { get; set; }
public string proc_gyro-magnitude_stats-std { get; set; }
public string proc_gyro-magnitude_stats-moment3 { get; set; }
public string proc_gyro-magnitude_stats-moment4 { get; set; }
public string proc_gyro-magnitude_stats-percentile25 { get; set; }
public string proc_gyro-magnitude_stats-percentile50 { get; set; }
public string proc_gyro-magnitude_stats-percentile75 { get; set; }
public string proc_gyro-magnitude_stats-value_entropy { get; set; }
public string proc_gyro-magnitude_stats-time_entropy { get; set; }
public string proc_gyro-magnitude_spectrum-log_energy_band0 { get; set; }
public string proc_gyro-magnitude_spectrum-log_energy_band1 { get; set; }
public string proc_gyro-magnitude_spectrum-log_energy_band2 { get; set; }
public string proc_gyro-magnitude_spectrum-log_energy_band3 { get; set; }
public string proc_gyro-magnitude_spectrum-log_energy_band4 { get; set; }
public string proc_gyro-magnitude_spectrum-spectral_entropy { get; set; }
public string proc_gyro-magnitude_autocorrelation-period { get; set; }
public string proc_gyro-magnitude_autocorrelation-normalized_ac { get; set; }
public string proc_gyro-3d-mean_x { get; set; }
public string proc_gyro-3d-mean_y { get; set; }
public string proc_gyro-3d-mean_z { get; set; }
public string proc_gyro-3d-std_x { get; set; }
public string proc_gyro-3d-std_y { get; set; }
public string proc_gyro-3d-std_z { get; set; }
public string proc_gyro-3d-ro_xy { get; set; }
public string proc_gyro-3d-ro_xz { get; set; }
public string proc_gyro-3d-ro_yz { get; set; }
public string raw_magnet-magnitude_stats-mean { get; set; }
public string raw_magnet-magnitude_stats-std { get; set; }
public string raw_magnet-magnitude_stats-moment3 { get; set; }
public string raw_magnet-magnitude_stats-moment4 { get; set; }
public string raw_magnet-magnitude_stats-percentile25 { get; set; }
public string raw_magnet-magnitude_stats-percentile50 { get; set; }
public string raw_magnet-magnitude_stats-percentile75 { get; set; }
public string raw_magnet-magnitude_stats-value_entropy { get; set; }
public string raw_magnet-magnitude_stats-time_entropy { get; set; }
public string raw_magnet-magnitude_spectrum-log_energy_band0 { get; set; }
public string raw_magnet-magnitude_spectrum-log_energy_band1 { get; set; }
public string raw_magnet-magnitude_spectrum-log_energy_band2 { get; set; }
public string raw_magnet-magnitude_spectrum-log_energy_band3 { get; set; }
public string raw_magnet-magnitude_spectrum-log_energy_band4 { get; set; }
public string raw_magnet-magnitude_spectrum-spectral_entropy { get; set; }
public string raw_magnet-magnitude_autocorrelation-period { get; set; }
public string raw_magnet-magnitude_autocorrelation-normalized_ac { get; set; }
public string raw_magnet-3d-mean_x { get; set; }
public string raw_magnet-3d-mean_y { get; set; }
public string raw_magnet-3d-mean_z { get; set; }
public string raw_magnet-3d-std_x { get; set; }
public string raw_magnet-3d-std_y { get; set; }
public string raw_magnet-3d-std_z { get; set; }
public string raw_magnet-3d-ro_xy { get; set; }
public string raw_magnet-3d-ro_xz { get; set; }
public string raw_magnet-3d-ro_yz { get; set; }
public string raw_magnet-avr_cosine_similarity_lag_range0 { get; set; }
public string raw_magnet-avr_cosine_similarity_lag_range1 { get; set; }
public string raw_magnet-avr_cosine_similarity_lag_range2 { get; set; }
public string raw_magnet-avr_cosine_similarity_lag_range3 { get; set; }
public string raw_magnet-avr_cosine_similarity_lag_range4 { get; set; }
public string watch_acceleration-magnitude_stats-mean { get; set; }
public string watch_acceleration-magnitude_stats-std { get; set; }
public string watch_acceleration-magnitude_stats-moment3 { get; set; }
public string watch_acceleration-magnitude_stats-moment4 { get; set; }
public string watch_acceleration-magnitude_stats-percentile25 { get; set; }
public string watch_acceleration-magnitude_stats-percentile50 { get; set; }
public string watch_acceleration-magnitude_stats-percentile75 { get; set; }
public string watch_acceleration-magnitude_stats-value_entropy { get; set; }
public string watch_acceleration-magnitude_stats-time_entropy { get; set; }
public string watch_acceleration-magnitude_spectrum-log_energy_band0 { get; set; }
public string watch_acceleration-magnitude_spectrum-log_energy_band1 { get; set; }
public string watch_acceleration-magnitude_spectrum-log_energy_band2 { get; set; }
public string watch_acceleration-magnitude_spectrum-log_energy_band3 { get; set; }
public string watch_acceleration-magnitude_spectrum-log_energy_band4 { get; set; }
public string watch_acceleration-magnitude_spectrum-spectral_entropy { get; set; }
public string watch_acceleration-magnitude_autocorrelation-period { get; set; }
public string watch_acceleration-magnitude_autocorrelation-normalized_ac { get; set; }
public string watch_acceleration-3d-mean_x { get; set; }
public string watch_acceleration-3d-mean_y { get; set; }
public string watch_acceleration-3d-mean_z { get; set; }
public string watch_acceleration-3d-std_x { get; set; }
public string watch_acceleration-3d-std_y { get; set; }
public string watch_acceleration-3d-std_z { get; set; }
public string watch_acceleration-3d-ro_xy { get; set; }
public string watch_acceleration-3d-ro_xz { get; set; }
public string watch_acceleration-3d-ro_yz { get; set; }
public string watch_acceleration-spectrum-x_log_energy_band0 { get; set; }
public string watch_acceleration-spectrum-x_log_energy_band1 { get; set; }
public string watch_acceleration-spectrum-x_log_energy_band2 { get; set; }
public string watch_acceleration-spectrum-x_log_energy_band3 { get; set; }
public string watch_acceleration-spectrum-x_log_energy_band4 { get; set; }
public string watch_acceleration-spectrum-y_log_energy_band0 { get; set; }
public string watch_acceleration-spectrum-y_log_energy_band1 { get; set; }
public string watch_acceleration-spectrum-y_log_energy_band2 { get; set; }
public string watch_acceleration-spectrum-y_log_energy_band3 { get; set; }
public string watch_acceleration-spectrum-y_log_energy_band4 { get; set; }
public string watch_acceleration-spectrum-z_log_energy_band0 { get; set; }
public string watch_acceleration-spectrum-z_log_energy_band1 { get; set; }
public string watch_acceleration-spectrum-z_log_energy_band2 { get; set; }
public string watch_acceleration-spectrum-z_log_energy_band3 { get; set; }
public string watch_acceleration-spectrum-z_log_energy_band4 { get; set; }
public string watch_acceleration-relative_directions-avr_cosine_similarity_lag_range0 { get; set; }
public string watch_acceleration-relative_directions-avr_cosine_similarity_lag_range1 { get; set; }
public string watch_acceleration-relative_directions-avr_cosine_similarity_lag_range2 { get; set; }
public string watch_acceleration-relative_directions-avr_cosine_similarity_lag_range3 { get; set; }
public string watch_acceleration-relative_directions-avr_cosine_similarity_lag_range4 { get; set; }
public string watch_heading-mean_cos { get; set; }
public string watch_heading-std_cos { get; set; }
public string watch_heading-mom3_cos { get; set; }
public string watch_heading-mom4_cos { get; set; }
public string watch_heading-mean_sin { get; set; }
public string watch_heading-std_sin { get; set; }
public string watch_heading-mom3_sin { get; set; }
public string watch_heading-mom4_sin { get; set; }
public string watch_heading-entropy_8bins { get; set; }
public string location-num_valid_updates { get; set; }
public string location-log_latitude_range { get; set; }
public string location-log_longitude_range { get; set; }
public string location-min_altitude { get; set; }
public string location-max_altitude { get; set; }
public string location-min_speed { get; set; }
public string location-max_speed { get; set; }
public string location-best_horizontal_accuracy { get; set; }
public string location-best_vertical_accuracy { get; set; }
public string location-diameter { get; set; }
public string location-log_diameter { get; set; }
public string location_quick_features-std_lat { get; set; }
public string location_quick_features-std_long { get; set; }
public string location_quick_features-lat_change { get; set; }
public string location_quick_features-long_change { get; set; }
public string location_quick_features-mean_abs_lat_deriv { get; set; }
public string location_quick_features-mean_abs_long_deriv { get; set; }
public string audio_naive-mfcc0-mean { get; set; }
public string audio_naive-mfcc1-mean { get; set; }
public string audio_naive-mfcc2-mean { get; set; }
public string audio_naive-mfcc3-mean { get; set; }
public string audio_naive-mfcc4-mean { get; set; }
public string audio_naive-mfcc5-mean { get; set; }
public string audio_naive-mfcc6-mean { get; set; }
public string audio_naive-mfcc7-mean { get; set; }
public string audio_naive-mfcc8-mean { get; set; }
public string audio_naive-mfcc9-mean { get; set; }
public string audio_naive-mfcc10-mean { get; set; }
public string audio_naive-mfcc11-mean { get; set; }
public string audio_naive-mfcc12-mean { get; set; }
public string audio_naive-mfcc0-std { get; set; }
public string audio_naive-mfcc1-std { get; set; }
public string audio_naive-mfcc2-std { get; set; }
public string audio_naive-mfcc3-std { get; set; }
public string audio_naive-mfcc4-std { get; set; }
public string audio_naive-mfcc5-std { get; set; }
public string audio_naive-mfcc6-std { get; set; }
public string audio_naive-mfcc7-std { get; set; }
public string audio_naive-mfcc8-std { get; set; }
public string audio_naive-mfcc9-std { get; set; }
public string audio_naive-mfcc10-std { get; set; }
public string audio_naive-mfcc11-std { get; set; }
public string audio_naive-mfcc12-std { get; set; }
public string audio_properties-max_abs_value { get; set; }
public string audio_properties-normalization_multiplier { get; set; }
public string discrete-app_state-is_active { get; set; }
public string discrete-app_state-is_inactive { get; set; }
public string discrete-app_state-is_background { get; set; }
public string discrete-app_state-missing { get; set; }
public string discrete-battery_plugged-is_ac { get; set; }
public string discrete-battery_plugged-is_usb { get; set; }
public string discrete-battery_plugged-is_wireless { get; set; }
public string discrete-battery_plugged-missing { get; set; }
public string discrete-battery_state-is_unknown { get; set; }
public string discrete-battery_state-is_unplugged { get; set; }
public string discrete-battery_state-is_not_charging { get; set; }
public string discrete-battery_state-is_discharging { get; set; }
public string discrete-battery_state-is_charging { get; set; }
public string discrete-battery_state-is_full { get; set; }
public string discrete-battery_state-missing { get; set; }
public string discrete-on_the_phone-is_False { get; set; }
public string discrete-on_the_phone-is_True { get; set; }
public string discrete-on_the_phone-missing { get; set; }
public string discrete-ringer_mode-is_normal { get; set; }
public string discrete-ringer_mode-is_silent_no_vibrate { get; set; }
public string discrete-ringer_mode-is_silent_with_vibrate { get; set; }
public string discrete-ringer_mode-missing { get; set; }
public string discrete-wifi_status-is_not_reachable { get; set; }
public string discrete-wifi_status-is_reachable_via_wifi { get; set; }
public string discrete-wifi_status-is_reachable_via_wwan { get; set; }
public string discrete-wifi_status-missing { get; set; }
public string lf_measurements-light { get; set; }
public string lf_measurements-pressure { get; set; }
public string lf_measurements-proximity_cm { get; set; }
public string lf_measurements-proximity { get; set; }
public string lf_measurements-relative_humidity { get; set; }
public string lf_measurements-battery_level { get; set; }
public string lf_measurements-screen_brightness { get; set; }
public string lf_measurements-temperature_ambient { get; set; }
public string discrete-time_of_day-between0and6 { get; set; }
public string discrete-time_of_day-between3and9 { get; set; }
public string discrete-time_of_day-between6and12 { get; set; }
public string discrete-time_of_day-between9and15 { get; set; }
public string discrete-time_of_day-between12and18 { get; set; }
public string discrete-time_of_day-between15and21 { get; set; }
public string discrete-time_of_day-between18and24 { get; set; }
public string discrete-time_of_day-between21and3 { get; set; }
public string label-LYING_DOWN { get; set; }
public string label-SITTING { get; set; }
public string label-FIX_walking { get; set; }
public string label-FIX_running { get; set; }
public string label-BICYCLING { get; set; }
public string label-SLEEPING { get; set; }
public string label-LAB_WORK { get; set; }
public string label-IN_CLASS { get; set; }
public string label-IN_A_MEETING { get; set; }
public string label-LOC_main_workplace { get; set; }
public string label-OR_indoors { get; set; }
public string label-OR_outside { get; set; }
public string label-IN_A_CAR { get; set; }
public string label-ON_A_BUS { get; set; }
public string label-DRIVE_-_I_M_THE_DRIVER { get; set; }
public string label-DRIVE_-_I_M_A_PASSENGER { get; set; }
public string label-LOC_home { get; set; }
public string label-FIX_restaurant { get; set; }
public string label-PHONE_IN_POCKET { get; set; }
public string label-OR_exercise { get; set; }
public string label-COOKING { get; set; }
public string label-SHOPPING { get; set; }
public string label-STROLLING { get; set; }
public string label-DRINKING__ALCOHOL_ { get; set; }
public string label-BATHING_-_SHOWER { get; set; }
public string label-CLEANING { get; set; }
public string label-DOING_LAUNDRY { get; set; }
public string label-WASHING_DISHES { get; set; }
public string label-WATCHING_TV { get; set; }
public string label-SURFING_THE_INTERNET { get; set; }
public string label-AT_A_PARTY { get; set; }
public string label-AT_A_BAR { get; set; }
public string label-LOC_beach { get; set; }
public string label-SINGING { get; set; }
public string label-TALKING { get; set; }
public string label-COMPUTER_WORK { get; set; }
public string label-EATING { get; set; }
public string label-TOILET { get; set; }
public string label-GROOMING { get; set; }
public string label-DRESSING { get; set; }
public string label-AT_THE_GYM { get; set; }
public string label-STAIRS_-_GOING_UP { get; set; }
public string label-STAIRS_-_GOING_DOWN { get; set; }
public string label-ELEVATOR { get; set; }
public string label-OR_standing { get; set; }
public string label-AT_SCHOOL { get; set; }
public string label-PHONE_IN_HAND { get; set; }
public string label-PHONE_IN_BAG { get; set; }
public string label-PHONE_ON_TABLE { get; set; }
public string label-WITH_CO-WORKERS { get; set; }
public string label-WITH_FRIENDS { get; set; }
public string label_source { get; set; }
}
