public class SensorValues {
public string timestamp { get; set; }
public string raw_acc_magnitude_stats_mean { get; set; }
public string raw_acc_magnitude_stats_std { get; set; }
public string raw_acc_magnitude_stats_moment3 { get; set; }
public string raw_acc_magnitude_stats_moment4 { get; set; }
public string raw_acc_magnitude_stats_percentile25 { get; set; }
public string raw_acc_magnitude_stats_percentile50 { get; set; }
public string raw_acc_magnitude_stats_percentile75 { get; set; }
public string raw_acc_magnitude_stats_value_entropy { get; set; }
public string raw_acc_magnitude_stats_time_entropy { get; set; }
public string raw_acc_magnitude_spectrum_log_energy_band0 { get; set; }
public string raw_acc_magnitude_spectrum_log_energy_band1 { get; set; }
public string raw_acc_magnitude_spectrum_log_energy_band2 { get; set; }
public string raw_acc_magnitude_spectrum_log_energy_band3 { get; set; }
public string raw_acc_magnitude_spectrum_log_energy_band4 { get; set; }
public string raw_acc_magnitude_spectrum_spectral_entropy { get; set; }
public string raw_acc_magnitude_autocorrelation_period { get; set; }
public string raw_acc_magnitude_autocorrelation_normalized_ac { get; set; }
public string raw_acc_3d_mean_x { get; set; }
public string raw_acc_3d_mean_y { get; set; }
public string raw_acc_3d_mean_z { get; set; }
public string raw_acc_3d_std_x { get; set; }
public string raw_acc_3d_std_y { get; set; }
public string raw_acc_3d_std_z { get; set; }
public string raw_acc_3d_ro_xy { get; set; }
public string raw_acc_3d_ro_xz { get; set; }
public string raw_acc_3d_ro_yz { get; set; }
public string proc_gyro_magnitude_stats_mean { get; set; }
public string proc_gyro_magnitude_stats_std { get; set; }
public string proc_gyro_magnitude_stats_moment3 { get; set; }
public string proc_gyro_magnitude_stats_moment4 { get; set; }
public string proc_gyro_magnitude_stats_percentile25 { get; set; }
public string proc_gyro_magnitude_stats_percentile50 { get; set; }
public string proc_gyro_magnitude_stats_percentile75 { get; set; }
public string proc_gyro_magnitude_stats_value_entropy { get; set; }
public string proc_gyro_magnitude_stats_time_entropy { get; set; }
public string proc_gyro_magnitude_spectrum_log_energy_band0 { get; set; }
public string proc_gyro_magnitude_spectrum_log_energy_band1 { get; set; }
public string proc_gyro_magnitude_spectrum_log_energy_band2 { get; set; }
public string proc_gyro_magnitude_spectrum_log_energy_band3 { get; set; }
public string proc_gyro_magnitude_spectrum_log_energy_band4 { get; set; }
public string proc_gyro_magnitude_spectrum_spectral_entropy { get; set; }
public string proc_gyro_magnitude_autocorrelation_period { get; set; }
public string proc_gyro_magnitude_autocorrelation_normalized_ac { get; set; }
public string proc_gyro_3d_mean_x { get; set; }
public string proc_gyro_3d_mean_y { get; set; }
public string proc_gyro_3d_mean_z { get; set; }
public string proc_gyro_3d_std_x { get; set; }
public string proc_gyro_3d_std_y { get; set; }
public string proc_gyro_3d_std_z { get; set; }
public string proc_gyro_3d_ro_xy { get; set; }
public string proc_gyro_3d_ro_xz { get; set; }
public string proc_gyro_3d_ro_yz { get; set; }
public string raw_magnet_magnitude_stats_mean { get; set; }
public string raw_magnet_magnitude_stats_std { get; set; }
public string raw_magnet_magnitude_stats_moment3 { get; set; }
public string raw_magnet_magnitude_stats_moment4 { get; set; }
public string raw_magnet_magnitude_stats_percentile25 { get; set; }
public string raw_magnet_magnitude_stats_percentile50 { get; set; }
public string raw_magnet_magnitude_stats_percentile75 { get; set; }
public string raw_magnet_magnitude_stats_value_entropy { get; set; }
public string raw_magnet_magnitude_stats_time_entropy { get; set; }
public string raw_magnet_magnitude_spectrum_log_energy_band0 { get; set; }
public string raw_magnet_magnitude_spectrum_log_energy_band1 { get; set; }
public string raw_magnet_magnitude_spectrum_log_energy_band2 { get; set; }
public string raw_magnet_magnitude_spectrum_log_energy_band3 { get; set; }
public string raw_magnet_magnitude_spectrum_log_energy_band4 { get; set; }
public string raw_magnet_magnitude_spectrum_spectral_entropy { get; set; }
public string raw_magnet_magnitude_autocorrelation_period { get; set; }
public string raw_magnet_magnitude_autocorrelation_normalized_ac { get; set; }
public string raw_magnet_3d_mean_x { get; set; }
public string raw_magnet_3d_mean_y { get; set; }
public string raw_magnet_3d_mean_z { get; set; }
public string raw_magnet_3d_std_x { get; set; }
public string raw_magnet_3d_std_y { get; set; }
public string raw_magnet_3d_std_z { get; set; }
public string raw_magnet_3d_ro_xy { get; set; }
public string raw_magnet_3d_ro_xz { get; set; }
public string raw_magnet_3d_ro_yz { get; set; }
public string raw_magnet_avr_cosine_similarity_lag_range0 { get; set; }
public string raw_magnet_avr_cosine_similarity_lag_range1 { get; set; }
public string raw_magnet_avr_cosine_similarity_lag_range2 { get; set; }
public string raw_magnet_avr_cosine_similarity_lag_range3 { get; set; }
public string raw_magnet_avr_cosine_similarity_lag_range4 { get; set; }
public string watch_acceleration_magnitude_stats_mean { get; set; }
public string watch_acceleration_magnitude_stats_std { get; set; }
public string watch_acceleration_magnitude_stats_moment3 { get; set; }
public string watch_acceleration_magnitude_stats_moment4 { get; set; }
public string watch_acceleration_magnitude_stats_percentile25 { get; set; }
public string watch_acceleration_magnitude_stats_percentile50 { get; set; }
public string watch_acceleration_magnitude_stats_percentile75 { get; set; }
public string watch_acceleration_magnitude_stats_value_entropy { get; set; }
public string watch_acceleration_magnitude_stats_time_entropy { get; set; }
public string watch_acceleration_magnitude_spectrum_log_energy_band0 { get; set; }
public string watch_acceleration_magnitude_spectrum_log_energy_band1 { get; set; }
public string watch_acceleration_magnitude_spectrum_log_energy_band2 { get; set; }
public string watch_acceleration_magnitude_spectrum_log_energy_band3 { get; set; }
public string watch_acceleration_magnitude_spectrum_log_energy_band4 { get; set; }
public string watch_acceleration_magnitude_spectrum_spectral_entropy { get; set; }
public string watch_acceleration_magnitude_autocorrelation_period { get; set; }
public string watch_acceleration_magnitude_autocorrelation_normalized_ac { get; set; }
public string watch_acceleration_3d_mean_x { get; set; }
public string watch_acceleration_3d_mean_y { get; set; }
public string watch_acceleration_3d_mean_z { get; set; }
public string watch_acceleration_3d_std_x { get; set; }
public string watch_acceleration_3d_std_y { get; set; }
public string watch_acceleration_3d_std_z { get; set; }
public string watch_acceleration_3d_ro_xy { get; set; }
public string watch_acceleration_3d_ro_xz { get; set; }
public string watch_acceleration_3d_ro_yz { get; set; }
public string watch_acceleration_spectrum_x_log_energy_band0 { get; set; }
public string watch_acceleration_spectrum_x_log_energy_band1 { get; set; }
public string watch_acceleration_spectrum_x_log_energy_band2 { get; set; }
public string watch_acceleration_spectrum_x_log_energy_band3 { get; set; }
public string watch_acceleration_spectrum_x_log_energy_band4 { get; set; }
public string watch_acceleration_spectrum_y_log_energy_band0 { get; set; }
public string watch_acceleration_spectrum_y_log_energy_band1 { get; set; }
public string watch_acceleration_spectrum_y_log_energy_band2 { get; set; }
public string watch_acceleration_spectrum_y_log_energy_band3 { get; set; }
public string watch_acceleration_spectrum_y_log_energy_band4 { get; set; }
public string watch_acceleration_spectrum_z_log_energy_band0 { get; set; }
public string watch_acceleration_spectrum_z_log_energy_band1 { get; set; }
public string watch_acceleration_spectrum_z_log_energy_band2 { get; set; }
public string watch_acceleration_spectrum_z_log_energy_band3 { get; set; }
public string watch_acceleration_spectrum_z_log_energy_band4 { get; set; }
public string watch_acceleration_relative_directions_avr_cosine_similarity_lag_range0 { get; set; }
public string watch_acceleration_relative_directions_avr_cosine_similarity_lag_range1 { get; set; }
public string watch_acceleration_relative_directions_avr_cosine_similarity_lag_range2 { get; set; }
public string watch_acceleration_relative_directions_avr_cosine_similarity_lag_range3 { get; set; }
public string watch_acceleration_relative_directions_avr_cosine_similarity_lag_range4 { get; set; }
public string watch_heading_mean_cos { get; set; }
public string watch_heading_std_cos { get; set; }
public string watch_heading_mom3_cos { get; set; }
public string watch_heading_mom4_cos { get; set; }
public string watch_heading_mean_sin { get; set; }
public string watch_heading_std_sin { get; set; }
public string watch_heading_mom3_sin { get; set; }
public string watch_heading_mom4_sin { get; set; }
public string watch_heading_entropy_8bins { get; set; }
public string location_num_valid_updates { get; set; }
public string location_log_latitude_range { get; set; }
public string location_log_longitude_range { get; set; }
public string location_min_altitude { get; set; }
public string location_max_altitude { get; set; }
public string location_min_speed { get; set; }
public string location_max_speed { get; set; }
public string location_best_horizontal_accuracy { get; set; }
public string location_best_vertical_accuracy { get; set; }
public string location_diameter { get; set; }
public string location_log_diameter { get; set; }
public string location_quick_features_std_lat { get; set; }
public string location_quick_features_std_long { get; set; }
public string location_quick_features_lat_change { get; set; }
public string location_quick_features_long_change { get; set; }
public string location_quick_features_mean_abs_lat_deriv { get; set; }
public string location_quick_features_mean_abs_long_deriv { get; set; }
public string audio_naive_mfcc0_mean { get; set; }
public string audio_naive_mfcc1_mean { get; set; }
public string audio_naive_mfcc2_mean { get; set; }
public string audio_naive_mfcc3_mean { get; set; }
public string audio_naive_mfcc4_mean { get; set; }
public string audio_naive_mfcc5_mean { get; set; }
public string audio_naive_mfcc6_mean { get; set; }
public string audio_naive_mfcc7_mean { get; set; }
public string audio_naive_mfcc8_mean { get; set; }
public string audio_naive_mfcc9_mean { get; set; }
public string audio_naive_mfcc10_mean { get; set; }
public string audio_naive_mfcc11_mean { get; set; }
public string audio_naive_mfcc12_mean { get; set; }
public string audio_naive_mfcc0_std { get; set; }
public string audio_naive_mfcc1_std { get; set; }
public string audio_naive_mfcc2_std { get; set; }
public string audio_naive_mfcc3_std { get; set; }
public string audio_naive_mfcc4_std { get; set; }
public string audio_naive_mfcc5_std { get; set; }
public string audio_naive_mfcc6_std { get; set; }
public string audio_naive_mfcc7_std { get; set; }
public string audio_naive_mfcc8_std { get; set; }
public string audio_naive_mfcc9_std { get; set; }
public string audio_naive_mfcc10_std { get; set; }
public string audio_naive_mfcc11_std { get; set; }
public string audio_naive_mfcc12_std { get; set; }
public string audio_properties_max_abs_value { get; set; }
public string audio_properties_normalization_multiplier { get; set; }
public string discrete_app_state_is_active { get; set; }
public string discrete_app_state_is_inactive { get; set; }
public string discrete_app_state_is_background { get; set; }
public string discrete_app_state_missing { get; set; }
public string discrete_battery_plugged_is_ac { get; set; }
public string discrete_battery_plugged_is_usb { get; set; }
public string discrete_battery_plugged_is_wireless { get; set; }
public string discrete_battery_plugged_missing { get; set; }
public string discrete_battery_state_is_unknown { get; set; }
public string discrete_battery_state_is_unplugged { get; set; }
public string discrete_battery_state_is_not_charging { get; set; }
public string discrete_battery_state_is_discharging { get; set; }
public string discrete_battery_state_is_charging { get; set; }
public string discrete_battery_state_is_full { get; set; }
public string discrete_battery_state_missing { get; set; }
public string discrete_on_the_phone_is_False { get; set; }
public string discrete_on_the_phone_is_True { get; set; }
public string discrete_on_the_phone_missing { get; set; }
public string discrete_ringer_mode_is_normal { get; set; }
public string discrete_ringer_mode_is_silent_no_vibrate { get; set; }
public string discrete_ringer_mode_is_silent_with_vibrate { get; set; }
public string discrete_ringer_mode_missing { get; set; }
public string discrete_wifi_status_is_not_reachable { get; set; }
public string discrete_wifi_status_is_reachable_via_wifi { get; set; }
public string discrete_wifi_status_is_reachable_via_wwan { get; set; }
public string discrete_wifi_status_missing { get; set; }
public string lf_measurements_light { get; set; }
public string lf_measurements_pressure { get; set; }
public string lf_measurements_proximity_cm { get; set; }
public string lf_measurements_proximity { get; set; }
public string lf_measurements_relative_humidity { get; set; }
public string lf_measurements_battery_level { get; set; }
public string lf_measurements_screen_brightness { get; set; }
public string lf_measurements_temperature_ambient { get; set; }
public string discrete_time_of_day_between0and6 { get; set; }
public string discrete_time_of_day_between3and9 { get; set; }
public string discrete_time_of_day_between6and12 { get; set; }
public string discrete_time_of_day_between9and15 { get; set; }
public string discrete_time_of_day_between12and18 { get; set; }
public string discrete_time_of_day_between15and21 { get; set; }
public string discrete_time_of_day_between18and24 { get; set; }
public string discrete_time_of_day_between21and3 { get; set; }
public string label_LYING_DOWN { get; set; }
public string label_SITTING { get; set; }
public string label_FIX_walking { get; set; }
public string label_FIX_running { get; set; }
public string label_BICYCLING { get; set; }
public string label_SLEEPING { get; set; }
public string label_LAB_WORK { get; set; }
public string label_IN_CLASS { get; set; }
public string label_IN_A_MEETING { get; set; }
public string label_LOC_main_workplace { get; set; }
public string label_OR_indoors { get; set; }
public string label_OR_outside { get; set; }
public string label_IN_A_CAR { get; set; }
public string label_ON_A_BUS { get; set; }
public string label_DRIVE___I_M_THE_DRIVER { get; set; }
public string label_DRIVE___I_M_A_PASSENGER { get; set; }
public string label_LOC_home { get; set; }
public string label_FIX_restaurant { get; set; }
public string label_PHONE_IN_POCKET { get; set; }
public string label_OR_exercise { get; set; }
public string label_COOKING { get; set; }
public string label_SHOPPING { get; set; }
public string label_STROLLING { get; set; }
public string label_DRINKING__ALCOHOL_ { get; set; }
public string label_BATHING___SHOWER { get; set; }
public string label_CLEANING { get; set; }
public string label_DOING_LAUNDRY { get; set; }
public string label_WASHING_DISHES { get; set; }
public string label_WATCHING_TV { get; set; }
public string label_SURFING_THE_INTERNET { get; set; }
public string label_AT_A_PARTY { get; set; }
public string label_AT_A_BAR { get; set; }
public string label_LOC_beach { get; set; }
public string label_SINGING { get; set; }
public string label_TALKING { get; set; }
public string label_COMPUTER_WORK { get; set; }
public string label_EATING { get; set; }
public string label_TOILET { get; set; }
public string label_GROOMING { get; set; }
public string label_DRESSING { get; set; }
public string label_AT_THE_GYM { get; set; }
public string label_STAIRS___GOING_UP { get; set; }
public string label_STAIRS___GOING_DOWN { get; set; }
public string label_ELEVATOR { get; set; }
public string label_OR_standing { get; set; }
public string label_AT_SCHOOL { get; set; }
public string label_PHONE_IN_HAND { get; set; }
public string label_PHONE_IN_BAG { get; set; }
public string label_PHONE_ON_TABLE { get; set; }
public string label_WITH_CO_WORKERS { get; set; }
public string label_WITH_FRIENDS { get; set; }
public string label_source { get; set; }
}
