FROM mcr.microsoft.com/dotnet/core/sdk:3.1

# copy and build source
WORKDIR /broker_listener_src

COPY BrokerListener/BrokerListener.csproj ./BrokerListener.csproj
COPY BrokerListener/Program.cs ./Program.cs

RUN dotnet publish --output /broker_listener_bin

ENTRYPOINT ["dotnet", "/broker_listener_bin/BrokerListener.dll"]