FROM python:latest

RUN pip install pika

WORKDIR /broker_listener

COPY ./scripts/general/broker_listener.py ./program.py

# default values for soa network
ARG broker_address_arg="soa-broker"
ARG broker_port_arg="5672"

ENV BROKER_ADDRESS=$broker_address_arg
ENV BROKER_PORT=$broker_port_arg

ENTRYPOINT ["python", "/broker_listener/program.py"]