#!/bin/bash

mongo soa_collector --eval '

	db.Sensors.aggregate(
		[
			{ 
				
				$match: {sensor_name:"sensor_3"}
		
			},
			{
				$project: {
					sensor_name:1,
					records:1	
				}
			}			
			
		]
	
	).forEach(printjson)

' | egrep --color "timestamp"
















